package com.example.demo.api;

import com.example.demo.model.Person;
import com.example.demo.service.PersonService;
import lombok.NonNull;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@Controller
@RequestMapping("api/v1/person")
@RestController
public class PersonController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data


    private  PersonService personService;
    @Autowired
    private PersonRepository personRepository;

    public PersonController(PersonService personService) {
        this.personService = personService;
    }

    @PostMapping
    public @ResponseBody Person addPerson(@NonNull @RequestBody Person person) {
            personService.addPerson(person);
            personRepository.save(person);
            return person;
    }

    @GetMapping
    public List<Person> getAllPeople() {
        return personService.getAllPeople();
    }

    @GetMapping(path = "{id}")
    public Person getPersonById(@PathVariable("id") int id) {
        return personService.getPersonById(id).orElse(null);
    }


    @DeleteMapping(path = "{id}")
    public void deletePersonById(@PathVariable("id") int id) {
        personService.deletePerson(id);
        if(personRepository.existsById(id)){
            Person person = personRepository.findById(id).get();
            personRepository.deleteById(id);
        }
    }

    @PutMapping(path = "{id}")
    public void updatePerson(@PathVariable("id") int id, @NonNull @RequestBody Person personToUpdate) {
        personService.updatePerson(id, personToUpdate);
        if(personRepository.existsById(id)){
            Person person = personRepository.findById(id).get();
            person.setName(personToUpdate.getName());
            personRepository.save(person);
        }
    }
}
